#ifndef   __zi16_H__
#define   __zi16_H__


extern code unsigned char hzli[];
extern code unsigned char hzdian[];
extern code unsigned char hzrong[];
extern code unsigned char hzliang[];
extern code unsigned char hzce[];
extern code unsigned char hzshi[];
extern code unsigned char hzya[];
extern code unsigned char hzliu[];
extern code unsigned char hzshe[];
extern code unsigned char hzzhi[];
extern code unsigned char hzfang[];
extern code unsigned char hzjie[];
extern code unsigned char hzshu[];
extern code unsigned char hzzhun[];
extern code unsigned char hztai[];
extern code unsigned char hzyi[];
extern code unsigned char hzchi[];

extern code unsigned char sn[][16];

extern code unsigned char fhmh[];
extern code unsigned char fhd[];

extern code unsigned char zmm[];
extern code unsigned char zmA[];
extern code unsigned char zmH[];

extern code unsigned char zmV[];
extern code unsigned char fhjt[];
extern code unsigned char hzting[];
extern code unsigned char hzzi[];
extern code unsigned char hzzhong[];

#endif  
